In [1]:
import pandas as pd
loan = pd.read_csv("EDA_output.csv")

In [6]:
#loan.describe().T
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 64 columns):
Unnamed: 0                        int64
Unnamed: 0.1                      int64
loan_amnt                         int64
term                              int64
int_rate                          float64
grade                             object
sub_grade                         object
emp_length                        float64
home_ownership                    object
annual_inc                        float64
verification_status               object
loan_status                       object
pymnt_plan                        object
purpose                           object
dti                               float64
delinq_2yrs                       float64
inq_last_6mths                    float64
mths_since_last_delinq            float64
open_acc                          float64
pub_rec                           float64
revol_bal                         int64
revol_util                        float64
total_acc                         float64
initial_list_status               object
out_prncp                         float64
total_pymnt                       float64
total_rec_int                     float64
total_rec_late_fee                float64
recoveries                        float64
last_pymnt_amnt                   float64
collections_12_mths_ex_med        float64
application_type                  object
acc_now_delinq                    float64
tot_cur_bal                       float64
mths_since_rcnt_il                float64
il_util                           float64
all_util                          float64
total_rev_hi_lim                  float64
avg_cur_bal                       float64
chargeoff_within_12_mths          float64
delinq_amnt                       float64
mo_sin_old_il_acct                float64
mo_sin_old_rev_tl_op              float64
mo_sin_rcnt_rev_tl_op             float64
mo_sin_rcnt_tl                    float64
mths_since_recent_bc              float64
mths_since_recent_inq             float64
mths_since_recent_revol_delinq    float64
num_actv_bc_tl                    float64
num_actv_rev_tl                   float64
num_bc_sats                       float64
num_bc_tl                         float64
num_il_tl                         float64
num_op_rev_tl                     float64
num_rev_accts                     float64
num_tl_op_past_12m                float64
pct_tl_nvr_dlq                    float64
percent_bc_gt_75                  float64
pub_rec_bankruptcies              float64
tax_liens                         float64
total_bc_limit                    float64
hardship_flag                     object
disbursement_method               object
debt_settlement_flag              object
dtypes: float64(47), int64(5), object(12)
memory usage: 1.1+ GB

In [7]:
loan_dummies = pd.get_dummies(loan,drop_first=True)

In [9]:
loan_dummies.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,2260668.0,1.130334e+06,652598.783512,0.00,565166.75,1130333.50,1695500.25,2260667.00
Unnamed: 0.1,2260668.0,1.130334e+06,652598.783512,0.00,565166.75,1130333.50,1695500.25,2260667.00
loan_amnt,2260668.0,1.504693e+04,9190.245488,500.00,8000.00,12900.00,20000.00,40000.00
term,2260668.0,4.291032e+01,10.867161,36.00,36.00,36.00,60.00,60.00
int_rate,2260668.0,1.309291e+01,4.832114,5.31,9.49,12.62,15.99,30.99
...,...,...,...,...,...,...,...,...
initial_list_status_w,2260668.0,6.792094e-01,0.466781,0.00,0.00,1.00,1.00,1.00
application_type_Joint App,2260668.0,5.339572e-02,0.224821,0.00,0.00,0.00,0.00,1.00
hardship_flag_Y,2260668.0,3.914772e-04,0.019782,0.00,0.00,0.00,0.00,1.00
disbursement_method_DirectPay,2260668.0,3.455704e-02,0.182655,0.00,0.00,0.00,0.00,1.00
debt_settlement_flag_Y,2260668.0,1.462223e-02,0.120035,0.00,0.00,0.00,0.00,1.00

In [8]:
#scale data
from sklearn import preprocessing
import numpy as np
X = loan_dummies.drop('int_rate', axis=1)
scaler = preprocessing.StandardScaler().fit(X)
X_scaled=scaler.transform(X)

In [11]:
y = loan['int_rate']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=.8, random_state=1)